#%RAML 1.0 Library
types:
  num:
    type: number
    example: 10
  list:
    type: array
    example: [1,2,3,4,5,6,7,8,9,10]
  value:
    type: string
    example: "camel Case"
  camelCase:
    type: string
    example: "camelCase"